### ISSUE TITLE
Game not translated.

### ISSUE THREAD

**Issue by GoldFury** [KCV-Localisation/KanColleViewer-Translations#16]
Just as the title says,the game doesn't translate at all.I have all translations in my "Translations" folder and i ticked all translations ON in the settings,i don't know what else to do.

**Comment by Yuubari** [comment]
What do you mean “game is not translated”? Where exactly are you looking for translations? Are you sure you read the README (the main page of the repository) and the FAQ?

**Comment by GoldFury** [comment]
I didn't notice the FAQ,i followed the instructions and looks like it's working now,thanks anyway.
