### ISSUE TITLE
My game is not translated at all.

### ISSUE THREAD

**Issue by acelohan** [KCV-Localisation/KanColleViewer-Translations#29]
As the title said, nothing translated in my KCV, ship names, quests, equip names,...
Pretty sure that my language setting is set to English, b/c other tabs are in English (Overview, Fleet,...etc)
And this only happen on my laptop, my desktop is still fine.
And funny thing that sometime it turned back to normal.
I'm using Windows 10.
Please help.
![untitled](https://cloud.githubusercontent.com/assets/13862190/9347971/d25e989a-465a-11e5-80de-31c63b2f11d1.png)

**Comment by Yuubari** [comment]
You probably did not read the [FAQ](https://github.com/KCV-Localisation/KanColleViewer/blob/master/FAQ.md).

**Comment by acelohan** [comment]
Thank, it's a shortcut problem :P
