### ISSUE TITLE
One-time quest B24 description

### ISSUE THREAD

**Issue by Selphos** [KCV-Localisation/KanColleViewer-Translations#3]
<Quest>
    <ID>248</ID>
    <JP-Name>「第三十駆逐隊」対潜哨戒！</JP-Name>
    <TR-Name>30th Destroyer Fleet's Anti-Submarine Patrol</TR-Name>
    <JP-Detail>「第三十駆逐隊(第二次)」は直ちに抜錨！鎮守府正面の対潜哨戒を実施せよ！</JP-Detail>
    <TR-Detail>Deploy Mutsuki (睦月), Yayoi (弥生), Uzuki (卯月) and Mochizuki (望月) to World 1-5.</TR-Detail>
  </Quest>

This quest actually has the same completion requirement as ID 244 (B22) - the deployed fleet has to reach the boss and finish it with a C rank or higher; just visiting 1-5 isn't enough.

**Comment by Yuubari** [comment]
Clarified in b6bc2b8ce6c02f0fb7de2e0da33c73d2427898bb.
