### ISSUE TITLE
Update fishing quests

### ISSUE THREAD

**Issue by gakada** [KCV-Localisation/KanColleViewer-Translations#34]
Last one:

    {"api_no":292,"api_category":2,"api_type":1,"api_state":2,"api_title":"秋刀魚漁：もっと頑張ってもいいのよ！","api_detail":"かなり大変だけれど、秋刀魚漁、もっともっと頑張ってもいいのよ！","api_get_material":[800,300,300,300],"api_bonus_flag":1,"api_progress_flag":0,"api_invalid_flag":0}

https://github.com/gakada/KanColleViewer-Translations/blob/master/Quests.xml#L995

also, it seems like you don't need to collect 3 + 10 + 30, but just have 3, 10 and 30 of those things in the inventory for first, second and third quest respectively.

**Comment by Yuubari** [comment]
I already have 292 and yes, it's the same as all the older quests with inventory items.

Your clarification seems good, I'll look into it tomorrow.

**Comment by Yuubari** [comment]
Fixed in 54dddbece677d4573410793dd7070bb65394e912 (along with the addition of the new ranking reward).
