### ISSUE TITLE
zh-CN re-support and zh-TW addon?

### ISSUE THREAD

**Issue by KyoriAsh** [KCV-Localisation/KanColleViewer-Translations#4]
Can you readd back zh-CN with addition of zh-TW? I plan to do the entire KCV to "Real" multilingual, including app title, app desc, etc.

**Comment by Yuubari** [comment]
You're free to submit PRs with fully translated XML sets. Upon checking them I'll see about granting you direct push access to this repository.

User interface translations are stored in the resource files in the main KCV repository.

**Comment by KyoriAsh** [comment]
Meanwhile, I found out not all strings are Japanese as of original. For example Title is 提督業は忙しい instead of KanColleViewer, and other un-Japanese localized strings when I choose language Japanese. This is due to what problem?

**Comment by Yuubari** [comment]
Some features are exclusive to Zharay's fork and do not exist in the original Japanese source code.

Window title itself is currently hard-coded.

**Comment by KyoriAsh** [comment]
Master translation files are Resources.xml and "Translate/" ?

**Comment by Yuubari** [comment]
I'm not quite following. The project has neither a file named Resources.xml nor a directory named Translate.

**Comment by KyoriAsh** [comment]
oh I mean here https://github.com/KCV-Localisation/KanColleViewer-Translations and https://github.com/Yuubari/KanColleViewer/tree/master/Grabacr07.KanColleViewer/Properties
*should be resources.resx

**Comment by Yuubari** [comment]
Resources.resx defines the default locale (ja-JP).

There are no master files for ship/equipment/etc. translations; the English translation which is at the top level is the most updated (I add new ship and equipment lines right after the update; quests are added whenever someone with my KCV build encounters a new one).
