### ISSUE TITLE
Operations.xml function

### ISSUE THREAD

**Issue by gakada** [KCV-Localisation/KanColleViewer-Translations#44]
I don't know how it's used now in your fork, but the suggestion is to not use it to identify maps and nodes (e.g., by `api_quest_name` and `api_enemy_info.api_deck_name`) as it's not possible generally and there is a better way. `api_maparea_id` and `api_mapinfo_no` (from `kcsapi_map_start`) can be used to construct strings such as `World 5-4` or `E-3`, while `api_no` can be converted to map labels (e.g., [gakada/KanColleViewer-Translations/Data.xml](https://github.com/gakada/KanColleViewer-Translations/blob/release/Data.xml), https://github.com/gakada/KanColleViewer/commit/e5ec8228b0ba47ccbabdd113dfecf79680d39f4a), then, if `Operations.xml` is still needed, it can provide real translations for `api_quest_name`, `api_enemy_info.api_deck_name`, etc. (these strings also used in BattleInfo plugin for example).

**Comment by Yuubari** [comment]
I actually never implemented translations for these in the 4.x rewrite. Feel free to implement whatever changes regarding these XML files you want.

**Comment by Yuubari** [comment]
Also, technically these XMLs are now obsolete for my fork as a completely different approach is now used to provide translation updates and whatnot.

**Comment by gakada** [comment]
I see, https://github.com/Yuubari/KanColleViewer/blob/translation/source/Plugins/Logger/Loggers.cs, those are in Japanese. Well, maybe you know, but just pointing out https://github.com/KC3Kai/KC3Kai/blob/master/src/data/edges.json, I think something like `5-4 O (Boss)` is more useful than `api_quest_name` / `api_deck_name` in logs, etc.

**Comment by Yuubari** [comment]
Better logging is indeed planned, but I don't quite have time right now to implement it.

**Comment by gakada** [comment]
Is it still useful to do pull requests here (for your fork)? I want to try adding translations for enemy ships and equips and see if BattleInfo plugin can use them without modifications.

**Comment by Yuubari** [comment]
I've actually added the translations for them in my new translations API and it works fine. You can grab the XMLs in the old syntax from the API server to avoid manually adding stuff.

[Equipment](http://kcvapi.koumakan.jp/api/equipment/) — new items including abyssal weaponry are at the bottom.
[Ships](http://kcvapi.koumakan.jp/api/ships/) — same as above.

**Comment by Yuubari** [comment]
Some enemy items are not added and I did not yet research why (technically my KCV should submit all untranslated strings but these somehow aren't inserted).

**Comment by gakada** [comment]
They also can be listed from `api_start2`, like

    var api = require("path/to/api_start2.json");
    // ship names
    for (var x of api.api_data.api_mst_ship) console.log(x.api_id, x.api_name);
    // equipment names
    for (var x of api.api_data.api_mst_slotitem) console.log(x.api_id, x.api_name);

For TLs my plan is to convert from wikia (it's in Lua, so also can be automated).

**Comment by Yuubari** [comment]
I know they can, I have a Python script that pulls untranslated strings but you can't do that for quests and I was too lazy to connect my local Python scripts with the database.
